version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
            docker run --rm -it -v $(pwd):/workspace denisura/phpab -o src/autoload.php src		
            docker run -v $(pwd):/app --rm phpunit/phpunit --bootstrap src/autoload.php tests
            docker info
            docker build -t php-site 
